package Modelos;
// Generated 01-may-2017 15:08:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Campania generated by hbm2java
 */
public class Campania  implements java.io.Serializable {


     private Integer camId;
     private Marcas marcas;
     private String camNombre;
     private Date camInicio;
     private Date camFin;
     private String camFoto;
     private int camDescuento;
     private Set<CampaniaRopa> campaniaRopas = new HashSet<CampaniaRopa>(0);

    public Campania() {
    }

	
    public Campania(Marcas marcas, String camNombre, Date camInicio, Date camFin, String camFoto, int camDescuento) {
        this.marcas = marcas;
        this.camNombre = camNombre;
        this.camInicio = camInicio;
        this.camFin = camFin;
        this.camFoto = camFoto;
        this.camDescuento = camDescuento;
    }
    public Campania(Marcas marcas, String camNombre, Date camInicio, Date camFin, String camFoto, int camDescuento, Set<CampaniaRopa> campaniaRopas) {
       this.marcas = marcas;
       this.camNombre = camNombre;
       this.camInicio = camInicio;
       this.camFin = camFin;
       this.camFoto = camFoto;
       this.camDescuento = camDescuento;
       this.campaniaRopas = campaniaRopas;
    }
   
    public Integer getCamId() {
        return this.camId;
    }
    
    public void setCamId(Integer camId) {
        this.camId = camId;
    }
    public Marcas getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Marcas marcas) {
        this.marcas = marcas;
    }
    public String getCamNombre() {
        return this.camNombre;
    }
    
    public void setCamNombre(String camNombre) {
        this.camNombre = camNombre;
    }
    public Date getCamInicio() {
        return this.camInicio;
    }
    
    public void setCamInicio(Date camInicio) {
        this.camInicio = camInicio;
    }
    public Date getCamFin() {
        return this.camFin;
    }
    
    public void setCamFin(Date camFin) {
        this.camFin = camFin;
    }
    public String getCamFoto() {
        return this.camFoto;
    }
    
    public void setCamFoto(String camFoto) {
        this.camFoto = camFoto;
    }
    public int getCamDescuento() {
        return this.camDescuento;
    }
    
    public void setCamDescuento(int camDescuento) {
        this.camDescuento = camDescuento;
    }
    public Set<CampaniaRopa> getCampaniaRopas() {
        return this.campaniaRopas;
    }
    
    public void setCampaniaRopas(Set<CampaniaRopa> campaniaRopas) {
        this.campaniaRopas = campaniaRopas;
    }




}


