package Modelos;
// Generated 01-oct-2016 14:05:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer catId;
     private String catDescripcion;
     private Set<RopaCategoria> ropaCategorias = new HashSet<RopaCategoria>(0);

    public Categoria() {
    }

    public Categoria(Integer catId, String catDescripcion) {
        this.catId = catId;
        this.catDescripcion = catDescripcion;
    }
    
    public Categoria(String catDescripcion, Set<RopaCategoria> ropaCategorias) {
       this.catDescripcion = catDescripcion;
       this.ropaCategorias = ropaCategorias;
    }
   
    public Integer getCatId() {
        return this.catId;
    }
    
    public void setCatId(Integer catId) {
        this.catId = catId;
    }
    public String getCatDescripcion() {
        return this.catDescripcion;
    }
    
    public void setCatDescripcion(String catDescripcion) {
        this.catDescripcion = catDescripcion;
    }
    public Set<RopaCategoria> getRopaCategorias() {
        return this.ropaCategorias;
    }
    
    public void setRopaCategorias(Set<RopaCategoria> ropaCategorias) {
        this.ropaCategorias = ropaCategorias;
    }




}


