package Modelos;
// Generated 27-oct-2016 17:23:17 by Hibernate Tools 4.3.1



/**
 * Cesta generated by hbm2java
 */
public class Cesta  implements java.io.Serializable {


     private Integer cestaId;
     private Ropa ropa;
     private Usuarios usuarios;
     private int cestaUnidades;

    public Cesta() {
    }

    public Cesta(Ropa ropa, Usuarios usuarios, int cestaUnidades) {
       this.ropa = ropa;
       this.usuarios = usuarios;
       this.cestaUnidades = cestaUnidades;
    }
   
    public Integer getCestaId() {
        return this.cestaId;
    }
    
    public void setCestaId(Integer cestaId) {
        this.cestaId = cestaId;
    }
    public Ropa getRopa() {
        return this.ropa;
    }
    
    public void setRopa(Ropa ropa) {
        this.ropa = ropa;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public int getCestaUnidades() {
        return this.cestaUnidades;
    }
    
    public void setCestaUnidades(int cestaUnidades) {
        this.cestaUnidades = cestaUnidades;
    }




}


