package Modelos;
// Generated 06-ene-2017 14:44:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Color generated by hbm2java
 */
public class Color  implements java.io.Serializable {


     private Integer colorId;
     private String colorDescripcion;
     private String colorFoto;
     private Set<Ropa> ropas = new HashSet<Ropa>(0);

    public Color() {
    }

	
    public Color(String colorDescripcion, String colorFoto) {
        this.colorDescripcion = colorDescripcion;
        this.colorFoto = colorFoto;
    }
    public Color(String colorDescripcion, String colorFoto, Set<Ropa> ropas) {
       this.colorDescripcion = colorDescripcion;
       this.colorFoto = colorFoto;
       this.ropas = ropas;
    }
   
    public Integer getColorId() {
        return this.colorId;
    }
    
    public void setColorId(Integer colorId) {
        this.colorId = colorId;
    }
    public String getColorDescripcion() {
        return this.colorDescripcion;
    }
    
    public void setColorDescripcion(String colorDescripcion) {
        this.colorDescripcion = colorDescripcion;
    }
    public String getColorFoto() {
        return this.colorFoto;
    }
    
    public void setColorFoto(String colorFoto) {
        this.colorFoto = colorFoto;
    }
    public Set<Ropa> getRopas() {
        return this.ropas;
    }
    
    public void setRopas(Set<Ropa> ropas) {
        this.ropas = ropas;
    }




}


