package Modelos;
// Generated 16-sep-2016 19:41:34 by Hibernate Tools 4.3.1



/**
 * Direcciones generated by hbm2java
 */
public class Direcciones  implements java.io.Serializable {


     private Integer dirId;
     private Usuarios usuarios;
     private String dirEnvio;
     private String dirTipoEnvio;

    public Direcciones() {
    }

    public Direcciones(Usuarios usuarios, String dirEnvio, String dirTipoEnvio) {
       this.usuarios = usuarios;
       this.dirEnvio = dirEnvio;
       this.dirTipoEnvio = dirTipoEnvio;
    }
   
    public Integer getDirId() {
        return this.dirId;
    }
    
    public void setDirId(Integer dirId) {
        this.dirId = dirId;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getDirEnvio() {
        return this.dirEnvio;
    }
    
    public void setDirEnvio(String dirEnvio) {
        this.dirEnvio = dirEnvio;
    }
    public String getDirTipoEnvio() {
        return this.dirTipoEnvio;
    }
    
    public void setDirTipoEnvio(String dirTipoEnvio) {
        this.dirTipoEnvio = dirTipoEnvio;
    }




}


