package Modelos;
// Generated 18-jun-2017 18:48:23 by Hibernate Tools 4.3.1



/**
 * FavoritosId generated by hbm2java
 */
public class FavoritosId  implements java.io.Serializable {


     private int favRoId;
     private int favUsuId;

    public FavoritosId() {
    }

    public FavoritosId(int favRoId, int favUsuId) {
       this.favRoId = favRoId;
       this.favUsuId = favUsuId;
    }
   
    public int getFavRoId() {
        return this.favRoId;
    }
    
    public void setFavRoId(int favRoId) {
        this.favRoId = favRoId;
    }
    public int getFavUsuId() {
        return this.favUsuId;
    }
    
    public void setFavUsuId(int favUsuId) {
        this.favUsuId = favUsuId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FavoritosId) ) return false;
		 FavoritosId castOther = ( FavoritosId ) other; 
         
		 return (this.getFavRoId()==castOther.getFavRoId())
 && (this.getFavUsuId()==castOther.getFavUsuId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFavRoId();
         result = 37 * result + this.getFavUsuId();
         return result;
   }   


}


