package Modelos;
// Generated 06-dic-2016 14:39:33 by Hibernate Tools 4.3.1



/**
 * Favoritos generated by hbm2java
 */
public class Favoritos  implements java.io.Serializable {


     private FavoritosId id;
     private Ropa ropa;
     private Usuarios usuarios;

    public Favoritos() {
    }

    public Favoritos(FavoritosId id, Ropa ropa, Usuarios usuarios) {
       this.id = id;
       this.ropa = ropa;
       this.usuarios = usuarios;
    }
   
    public FavoritosId getId() {
        return this.id;
    }
    
    public void setId(FavoritosId id) {
        this.id = id;
    }
    public Ropa getRopa() {
        return this.ropa;
    }
    
    public void setRopa(Ropa ropa) {
        this.ropa = ropa;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }




}


