package Modelos;
// Generated 01-oct-2016 14:05:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marcas generated by hbm2java
 */
public class Marcas  implements java.io.Serializable {


     private Integer marcaId;
     private String marcaNombre;
     private Set<Ropa> ropas = new HashSet<Ropa>(0);

    public Marcas() {
    }

	
    public Marcas(String marcaNombre) {
        this.marcaNombre = marcaNombre;
    }
    public Marcas(String marcaNombre, Set<Ropa> ropas) {
       this.marcaNombre = marcaNombre;
       this.ropas = ropas;
    }
   
    public Integer getMarcaId() {
        return this.marcaId;
    }
    
    public void setMarcaId(Integer marcaId) {
        this.marcaId = marcaId;
    }
    public String getMarcaNombre() {
        return this.marcaNombre;
    }
    
    public void setMarcaNombre(String marcaNombre) {
        this.marcaNombre = marcaNombre;
    }
    public Set<Ropa> getRopas() {
        return this.ropas;
    }
    
    public void setRopas(Set<Ropa> ropas) {
        this.ropas = ropas;
    }




}


