package Modelos;
// Generated 18-jun-2017 18:48:23 by Hibernate Tools 4.3.1



/**
 * NoLogFavoritos generated by hbm2java
 */
public class NoLogFavoritos  implements java.io.Serializable {


     private NoLogFavoritosId id;
     private NoLogUsuarios noLogUsuarios;
     private Ropa ropa;

    public NoLogFavoritos() {
    }

    public NoLogFavoritos(NoLogFavoritosId id, NoLogUsuarios noLogUsuarios, Ropa ropa) {
       this.id = id;
       this.noLogUsuarios = noLogUsuarios;
       this.ropa = ropa;
    }
   
    public NoLogFavoritosId getId() {
        return this.id;
    }
    
    public void setId(NoLogFavoritosId id) {
        this.id = id;
    }
    public NoLogUsuarios getNoLogUsuarios() {
        return this.noLogUsuarios;
    }
    
    public void setNoLogUsuarios(NoLogUsuarios noLogUsuarios) {
        this.noLogUsuarios = noLogUsuarios;
    }
    public Ropa getRopa() {
        return this.ropa;
    }
    
    public void setRopa(Ropa ropa) {
        this.ropa = ropa;
    }




}


