package Modelos;
// Generated 14-may-2017 23:58:02 by Hibernate Tools 4.3.1



/**
 * NoLogFavoritosId generated by hbm2java
 */
public class NoLogFavoritosId  implements java.io.Serializable {


     private int nlfRoId;
     private int nlfNluUsuId;

    public NoLogFavoritosId() {
    }

    public NoLogFavoritosId(int nlfRoId, int nlfNluUsuId) {
       this.nlfRoId = nlfRoId;
       this.nlfNluUsuId = nlfNluUsuId;
    }
   
    public int getNlfRoId() {
        return this.nlfRoId;
    }
    
    public void setNlfRoId(int nlfRoId) {
        this.nlfRoId = nlfRoId;
    }
    public int getNlfNluUsuId() {
        return this.nlfNluUsuId;
    }
    
    public void setNlfNluUsuId(int nlfNluUsuId) {
        this.nlfNluUsuId = nlfNluUsuId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NoLogFavoritosId) ) return false;
		 NoLogFavoritosId castOther = ( NoLogFavoritosId ) other; 
         
		 return (this.getNlfRoId()==castOther.getNlfRoId())
 && (this.getNlfNluUsuId()==castOther.getNlfNluUsuId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNlfRoId();
         result = 37 * result + this.getNlfNluUsuId();
         return result;
   }   


}


