package Modelos;
// Generated 18-jun-2017 18:48:23 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NoLogUsuarios generated by hbm2java
 */
public class NoLogUsuarios  implements java.io.Serializable {


     private Integer nluUsuId;
     private String nluNick;
     private Date nluFechaCreacion;
     private String nluEmail;
     private Set<NoLogCesta> noLogCestas = new HashSet<NoLogCesta>(0);
     private Set<NoLogFavoritos> noLogFavoritoses = new HashSet<NoLogFavoritos>(0);

    public NoLogUsuarios() {
    }

	
    public NoLogUsuarios(String nluNick, Date nluFechaCreacion, String nluEmail) {
        this.nluNick = nluNick;
        this.nluFechaCreacion = nluFechaCreacion;
        this.nluEmail = nluEmail;
    }
    public NoLogUsuarios(String nluNick, Date nluFechaCreacion, String nluEmail, Set<NoLogCesta> noLogCestas, Set<NoLogFavoritos> noLogFavoritoses) {
       this.nluNick = nluNick;
       this.nluFechaCreacion = nluFechaCreacion;
       this.nluEmail = nluEmail;
       this.noLogCestas = noLogCestas;
       this.noLogFavoritoses = noLogFavoritoses;
    }
   
    public Integer getNluUsuId() {
        return this.nluUsuId;
    }
    
    public void setNluUsuId(Integer nluUsuId) {
        this.nluUsuId = nluUsuId;
    }
    public String getNluNick() {
        return this.nluNick;
    }
    
    public void setNluNick(String nluNick) {
        this.nluNick = nluNick;
    }
    public Date getNluFechaCreacion() {
        return this.nluFechaCreacion;
    }
    
    public void setNluFechaCreacion(Date nluFechaCreacion) {
        this.nluFechaCreacion = nluFechaCreacion;
    }
    public String getNluEmail() {
        return this.nluEmail;
    }
    
    public void setNluEmail(String nluEmail) {
        this.nluEmail = nluEmail;
    }
    public Set<NoLogCesta> getNoLogCestas() {
        return this.noLogCestas;
    }
    
    public void setNoLogCestas(Set<NoLogCesta> noLogCestas) {
        this.noLogCestas = noLogCestas;
    }
    public Set<NoLogFavoritos> getNoLogFavoritoses() {
        return this.noLogFavoritoses;
    }
    
    public void setNoLogFavoritoses(Set<NoLogFavoritos> noLogFavoritoses) {
        this.noLogFavoritoses = noLogFavoritoses;
    }




}


