package Modelos;
// Generated 14-may-2017 23:58:02 by Hibernate Tools 4.3.1



/**
 * NoLogCesta generated by hbm2java
 */
public class NoLogCesta  implements java.io.Serializable {


     private Integer nlcId;
     private NoLogUsuarios noLogUsuarios;
     private RopaStock ropaStock;
     private int nlcUnidades;

    public NoLogCesta() {
    }

    public NoLogCesta(NoLogUsuarios noLogUsuarios, RopaStock ropaStock, int nlcUnidades) {
       this.noLogUsuarios = noLogUsuarios;
       this.ropaStock = ropaStock;
       this.nlcUnidades = nlcUnidades;
    }
   
    public Integer getNlcId() {
        return this.nlcId;
    }
    
    public void setNlcId(Integer nlcId) {
        this.nlcId = nlcId;
    }
    public NoLogUsuarios getNoLogUsuarios() {
        return this.noLogUsuarios;
    }
    
    public void setNoLogUsuarios(NoLogUsuarios noLogUsuarios) {
        this.noLogUsuarios = noLogUsuarios;
    }
    public RopaStock getRopaStock() {
        return this.ropaStock;
    }
    
    public void setRopaStock(RopaStock ropaStock) {
        this.ropaStock = ropaStock;
    }
    public int getNlcUnidades() {
        return this.nlcUnidades;
    }
    
    public void setNlcUnidades(int nlcUnidades) {
        this.nlcUnidades = nlcUnidades;
    }




}


