package Modelos;
// Generated 16-sep-2016 19:41:34 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ofertas generated by hbm2java
 */
public class Ofertas  implements java.io.Serializable {


     private Integer ofertaId;
     private int ofertaDescuento;
     private Date ofertaFechaInicio;
     private Date ofertaFechaFin;
     private Set<Productos> productoses = new HashSet<Productos>(0);

    public Ofertas() {
    }

	
    public Ofertas(int ofertaDescuento, Date ofertaFechaInicio, Date ofertaFechaFin) {
        this.ofertaDescuento = ofertaDescuento;
        this.ofertaFechaInicio = ofertaFechaInicio;
        this.ofertaFechaFin = ofertaFechaFin;
    }
    public Ofertas(int ofertaDescuento, Date ofertaFechaInicio, Date ofertaFechaFin, Set<Productos> productoses) {
       this.ofertaDescuento = ofertaDescuento;
       this.ofertaFechaInicio = ofertaFechaInicio;
       this.ofertaFechaFin = ofertaFechaFin;
       this.productoses = productoses;
    }
   
    public Integer getOfertaId() {
        return this.ofertaId;
    }
    
    public void setOfertaId(Integer ofertaId) {
        this.ofertaId = ofertaId;
    }
    public int getOfertaDescuento() {
        return this.ofertaDescuento;
    }
    
    public void setOfertaDescuento(int ofertaDescuento) {
        this.ofertaDescuento = ofertaDescuento;
    }
    public Date getOfertaFechaInicio() {
        return this.ofertaFechaInicio;
    }
    
    public void setOfertaFechaInicio(Date ofertaFechaInicio) {
        this.ofertaFechaInicio = ofertaFechaInicio;
    }
    public Date getOfertaFechaFin() {
        return this.ofertaFechaFin;
    }
    
    public void setOfertaFechaFin(Date ofertaFechaFin) {
        this.ofertaFechaFin = ofertaFechaFin;
    }
    public Set<Productos> getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set<Productos> productoses) {
        this.productoses = productoses;
    }




}


