package Modelos;
// Generated 16-sep-2016 19:41:34 by Hibernate Tools 4.3.1



/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private Integer pedId;
     private Usuarios usuarios;
     private String pedFormaPago;

    public Pedidos() {
    }

    public Pedidos(Usuarios usuarios, String pedFormaPago) {
       this.usuarios = usuarios;
       this.pedFormaPago = pedFormaPago;
    }
   
    public Integer getPedId() {
        return this.pedId;
    }
    
    public void setPedId(Integer pedId) {
        this.pedId = pedId;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getPedFormaPago() {
        return this.pedFormaPago;
    }
    
    public void setPedFormaPago(String pedFormaPago) {
        this.pedFormaPago = pedFormaPago;
    }




}


