package Modelos;
// Generated 16-sep-2016 19:41:34 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer prodId;
     private Ofertas ofertas;
     private Secciones secciones;
     private String prodNombre;
     private double prodPrecio;
     private int prodStock;
     private Date prodFechaAlta;
     private String foto;

    public Productos() {
    }

    public Productos(Ofertas ofertas, Secciones secciones, String prodNombre, double prodPrecio, int prodStock, Date prodFechaAlta, String foto) {
       this.ofertas = ofertas;
       this.secciones = secciones;
       this.prodNombre = prodNombre;
       this.prodPrecio = prodPrecio;
       this.prodStock = prodStock;
       this.prodFechaAlta = prodFechaAlta;
       this.foto = foto;
    }
   
    public Integer getProdId() {
        return this.prodId;
    }
    
    public void setProdId(Integer prodId) {
        this.prodId = prodId;
    }
    public Ofertas getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Ofertas ofertas) {
        this.ofertas = ofertas;
    }
    public Secciones getSecciones() {
        return this.secciones;
    }
    
    public void setSecciones(Secciones secciones) {
        this.secciones = secciones;
    }
    public String getProdNombre() {
        return this.prodNombre;
    }
    
    public void setProdNombre(String prodNombre) {
        this.prodNombre = prodNombre;
    }
    public double getProdPrecio() {
        return this.prodPrecio;
    }
    
    public void setProdPrecio(double prodPrecio) {
        this.prodPrecio = prodPrecio;
    }
    public int getProdStock() {
        return this.prodStock;
    }
    
    public void setProdStock(int prodStock) {
        this.prodStock = prodStock;
    }
    public Date getProdFechaAlta() {
        return this.prodFechaAlta;
    }
    
    public void setProdFechaAlta(Date prodFechaAlta) {
        this.prodFechaAlta = prodFechaAlta;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }




}


