package Modelos;
// Generated 01-oct-2016 9:25:16 by Hibernate Tools 4.3.1



/**
 * RopaMaterialId generated by hbm2java
 */
public class RopaMaterialId  implements java.io.Serializable {


     private int romaRoId;
     private int romaMaterialId;

    public RopaMaterialId() {
    }

    public RopaMaterialId(int romaRoId, int romaMaterialId) {
       this.romaRoId = romaRoId;
       this.romaMaterialId = romaMaterialId;
    }
   
    public int getRomaRoId() {
        return this.romaRoId;
    }
    
    public void setRomaRoId(int romaRoId) {
        this.romaRoId = romaRoId;
    }
    public int getRomaMaterialId() {
        return this.romaMaterialId;
    }
    
    public void setRomaMaterialId(int romaMaterialId) {
        this.romaMaterialId = romaMaterialId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RopaMaterialId) ) return false;
		 RopaMaterialId castOther = ( RopaMaterialId ) other; 
         
		 return (this.getRomaRoId()==castOther.getRomaRoId())
 && (this.getRomaMaterialId()==castOther.getRomaMaterialId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRomaRoId();
         result = 37 * result + this.getRomaMaterialId();
         return result;
   }   


}


