package Modelos;
// Generated 06-abr-2017 19:59:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ropa generated by hbm2java
 */
public class Ropa  implements java.io.Serializable {


     private Integer roId;
     private Categoria categoria;
     private Clientela clientela;
     private Coleccion coleccion;
     private Look look;
     private Marcas marcas;
     private Subcategoria subcategoria;
     private String roDescripcion;
     private double roPrecio;
     private int roDescuento;
     private String roCaracteristicas;
     private byte roVisible;
     private Set<Favoritos> favoritoses = new HashSet<Favoritos>(0);
     private Set<RopaStock> ropaStocks = new HashSet<RopaStock>(0);
     private Set<CampaniaRopa> campaniaRopas = new HashSet<CampaniaRopa>(0);
     private Set<Fotos> fotoses = new HashSet<Fotos>(0);

    public Ropa() {
    }

	
    public Ropa(Categoria categoria, Clientela clientela, Coleccion coleccion, Look look, Marcas marcas, Subcategoria subcategoria, String roDescripcion, double roPrecio, int roDescuento, String roCaracteristicas, byte roVisible) {
        this.categoria = categoria;
        this.clientela = clientela;
        this.coleccion = coleccion;
        this.look = look;
        this.marcas = marcas;
        this.subcategoria = subcategoria;
        this.roDescripcion = roDescripcion;
        this.roPrecio = roPrecio;
        this.roDescuento = roDescuento;
        this.roCaracteristicas = roCaracteristicas;
        this.roVisible = roVisible;
    }
    public Ropa(Categoria categoria, Clientela clientela, Coleccion coleccion, Look look, Marcas marcas, Subcategoria subcategoria, String roDescripcion, double roPrecio, int roDescuento, String roCaracteristicas, byte roVisible, Set<Favoritos> favoritoses, Set<RopaStock> ropaStocks, Set<CampaniaRopa> campaniaRopas, Set<Fotos> fotoses) {
       this.categoria = categoria;
       this.clientela = clientela;
       this.coleccion = coleccion;
       this.look = look;
       this.marcas = marcas;
       this.subcategoria = subcategoria;
       this.roDescripcion = roDescripcion;
       this.roPrecio = roPrecio;
       this.roDescuento = roDescuento;
       this.roCaracteristicas = roCaracteristicas;
       this.roVisible = roVisible;
       this.favoritoses = favoritoses;
       this.ropaStocks = ropaStocks;
       this.campaniaRopas = campaniaRopas;
       this.fotoses = fotoses;
    }
   
    public Integer getRoId() {
        return this.roId;
    }
    
    public void setRoId(Integer roId) {
        this.roId = roId;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Clientela getClientela() {
        return this.clientela;
    }
    
    public void setClientela(Clientela clientela) {
        this.clientela = clientela;
    }
    public Coleccion getColeccion() {
        return this.coleccion;
    }
    
    public void setColeccion(Coleccion coleccion) {
        this.coleccion = coleccion;
    }
    public Look getLook() {
        return this.look;
    }
    
    public void setLook(Look look) {
        this.look = look;
    }
    public Marcas getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Marcas marcas) {
        this.marcas = marcas;
    }
    public Subcategoria getSubcategoria() {
        return this.subcategoria;
    }
    
    public void setSubcategoria(Subcategoria subcategoria) {
        this.subcategoria = subcategoria;
    }
    public String getRoDescripcion() {
        return this.roDescripcion;
    }
    
    public void setRoDescripcion(String roDescripcion) {
        this.roDescripcion = roDescripcion;
    }
    public double getRoPrecio() {
        return this.roPrecio;
    }
    
    public void setRoPrecio(double roPrecio) {
        this.roPrecio = roPrecio;
    }
    public int getRoDescuento() {
        return this.roDescuento;
    }
    
    public void setRoDescuento(int roDescuento) {
        this.roDescuento = roDescuento;
    }
    public String getRoCaracteristicas() {
        return this.roCaracteristicas;
    }
    
    public void setRoCaracteristicas(String roCaracteristicas) {
        this.roCaracteristicas = roCaracteristicas;
    }
    public byte getRoVisible() {
        return this.roVisible;
    }
    
    public void setRoVisible(byte roVisible) {
        this.roVisible = roVisible;
    }
    public Set<Favoritos> getFavoritoses() {
        return this.favoritoses;
    }
    
    public void setFavoritoses(Set<Favoritos> favoritoses) {
        this.favoritoses = favoritoses;
    }
    public Set<RopaStock> getRopaStocks() {
        return this.ropaStocks;
    }
    
    public void setRopaStocks(Set<RopaStock> ropaStocks) {
        this.ropaStocks = ropaStocks;
    }
    public Set<CampaniaRopa> getCampaniaRopas() {
        return this.campaniaRopas;
    }
    
    public void setCampaniaRopas(Set<CampaniaRopa> campaniaRopas) {
        this.campaniaRopas = campaniaRopas;
    }
    public Set<Fotos> getFotoses() {
        return this.fotoses;
    }
    
    public void setFotoses(Set<Fotos> fotoses) {
        this.fotoses = fotoses;
    }




}


