package Modelos;
// Generated 06-abr-2017 19:59:16 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RopaStock generated by hbm2java
 */
public class RopaStock  implements java.io.Serializable {


     private Integer rostockId;
     private Color color;
     private Ropa ropa;
     private Tallas tallas;
     private int rostockUnidades;
     private Date rostockFecha;
     private Set<Cesta> cestas = new HashSet<Cesta>(0);

    public RopaStock() {
    }

	
    public RopaStock(Color color, Ropa ropa, Tallas tallas, int rostockUnidades, Date rostockFecha) {
        this.color = color;
        this.ropa = ropa;
        this.tallas = tallas;
        this.rostockUnidades = rostockUnidades;
        this.rostockFecha = rostockFecha;
    }
    public RopaStock(Color color, Ropa ropa, Tallas tallas, int rostockUnidades, Date rostockFecha, Set<Cesta> cestas) {
       this.color = color;
       this.ropa = ropa;
       this.tallas = tallas;
       this.rostockUnidades = rostockUnidades;
       this.rostockFecha = rostockFecha;
       this.cestas = cestas;
    }
   
    public Integer getRostockId() {
        return this.rostockId;
    }
    
    public void setRostockId(Integer rostockId) {
        this.rostockId = rostockId;
    }
    public Color getColor() {
        return this.color;
    }
    
    public void setColor(Color color) {
        this.color = color;
    }
    public Ropa getRopa() {
        return this.ropa;
    }
    
    public void setRopa(Ropa ropa) {
        this.ropa = ropa;
    }
    public Tallas getTallas() {
        return this.tallas;
    }
    
    public void setTallas(Tallas tallas) {
        this.tallas = tallas;
    }
    public int getRostockUnidades() {
        return this.rostockUnidades;
    }
    
    public void setRostockUnidades(int rostockUnidades) {
        this.rostockUnidades = rostockUnidades;
    }
    public Date getRostockFecha() {
        return this.rostockFecha;
    }
    
    public void setRostockFecha(Date rostockFecha) {
        this.rostockFecha = rostockFecha;
    }
    public Set<Cesta> getCestas() {
        return this.cestas;
    }
    
    public void setCestas(Set<Cesta> cestas) {
        this.cestas = cestas;
    }




}


