package Modelos;
// Generated 16-sep-2016 19:41:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Secciones generated by hbm2java
 */
public class Secciones  implements java.io.Serializable {


     private Integer seccId;
     private String seccNombre;
     private String seccGenero;
     private Set<Productos> productoses = new HashSet<Productos>(0);

    public Secciones() {
    }

	
    public Secciones(String seccNombre, String seccGenero) {
        this.seccNombre = seccNombre;
        this.seccGenero = seccGenero;
    }
    public Secciones(String seccNombre, String seccGenero, Set<Productos> productoses) {
       this.seccNombre = seccNombre;
       this.seccGenero = seccGenero;
       this.productoses = productoses;
    }
   
    public Integer getSeccId() {
        return this.seccId;
    }
    
    public void setSeccId(Integer seccId) {
        this.seccId = seccId;
    }
    public String getSeccNombre() {
        return this.seccNombre;
    }
    
    public void setSeccNombre(String seccNombre) {
        this.seccNombre = seccNombre;
    }
    public String getSeccGenero() {
        return this.seccGenero;
    }
    
    public void setSeccGenero(String seccGenero) {
        this.seccGenero = seccGenero;
    }
    public Set<Productos> getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set<Productos> productoses) {
        this.productoses = productoses;
    }




}


