package Modelos;
// Generated 18-jun-2017 18:48:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tallas generated by hbm2java
 */
public class Tallas  implements java.io.Serializable {


     private Integer tallaId;
     private String tallaDescripcion;
     private Set<RopaStock> ropaStocks = new HashSet<RopaStock>(0);

    public Tallas() {
    }

	
    public Tallas(String tallaDescripcion) {
        this.tallaDescripcion = tallaDescripcion;
    }
    public Tallas(String tallaDescripcion, Set<RopaStock> ropaStocks) {
       this.tallaDescripcion = tallaDescripcion;
       this.ropaStocks = ropaStocks;
    }
   
    public Integer getTallaId() {
        return this.tallaId;
    }
    
    public void setTallaId(Integer tallaId) {
        this.tallaId = tallaId;
    }
    public String getTallaDescripcion() {
        return this.tallaDescripcion;
    }
    
    public void setTallaDescripcion(String tallaDescripcion) {
        this.tallaDescripcion = tallaDescripcion;
    }
    public Set<RopaStock> getRopaStocks() {
        return this.ropaStocks;
    }
    
    public void setRopaStocks(Set<RopaStock> ropaStocks) {
        this.ropaStocks = ropaStocks;
    }




}


