package Modelos;
// Generated 16-sep-2016 19:41:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer usuId;
     private String usuNombre;
     private String usuApellidos;
     private String usuDni;
     private int usuEdad;
     private String usuGenero;
     private String usuEmail;
     private String usuLogin;
     private String usuClave;
     private Set<Pedidos> pedidoses = new HashSet<Pedidos>(0);
     private Set<Direcciones> direccioneses = new HashSet<Direcciones>(0);

    public Usuarios() {
    }

	
    public Usuarios(String usuNombre, String usuApellidos, String usuDni, int usuEdad, String usuGenero, String usuEmail, String usuLogin, String usuClave) {
        this.usuNombre = usuNombre;
        this.usuApellidos = usuApellidos;
        this.usuDni = usuDni;
        this.usuEdad = usuEdad;
        this.usuGenero = usuGenero;
        this.usuEmail = usuEmail;
        this.usuLogin = usuLogin;
        this.usuClave = usuClave;
    }
    public Usuarios(String usuNombre, String usuApellidos, String usuDni, int usuEdad, String usuGenero, String usuEmail, String usuLogin, String usuClave, Set<Pedidos> pedidoses, Set<Direcciones> direccioneses) {
       this.usuNombre = usuNombre;
       this.usuApellidos = usuApellidos;
       this.usuDni = usuDni;
       this.usuEdad = usuEdad;
       this.usuGenero = usuGenero;
       this.usuEmail = usuEmail;
       this.usuLogin = usuLogin;
       this.usuClave = usuClave;
       this.pedidoses = pedidoses;
       this.direccioneses = direccioneses;
    }
   
    public Integer getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(Integer usuId) {
        this.usuId = usuId;
    }
    public String getUsuNombre() {
        return this.usuNombre;
    }
    
    public void setUsuNombre(String usuNombre) {
        this.usuNombre = usuNombre;
    }
    public String getUsuApellidos() {
        return this.usuApellidos;
    }
    
    public void setUsuApellidos(String usuApellidos) {
        this.usuApellidos = usuApellidos;
    }
    public String getUsuDni() {
        return this.usuDni;
    }
    
    public void setUsuDni(String usuDni) {
        this.usuDni = usuDni;
    }
    public int getUsuEdad() {
        return this.usuEdad;
    }
    
    public void setUsuEdad(int usuEdad) {
        this.usuEdad = usuEdad;
    }
    public String getUsuGenero() {
        return this.usuGenero;
    }
    
    public void setUsuGenero(String usuGenero) {
        this.usuGenero = usuGenero;
    }
    public String getUsuEmail() {
        return this.usuEmail;
    }
    
    public void setUsuEmail(String usuEmail) {
        this.usuEmail = usuEmail;
    }
    public String getUsuLogin() {
        return this.usuLogin;
    }
    
    public void setUsuLogin(String usuLogin) {
        this.usuLogin = usuLogin;
    }
    public String getUsuClave() {
        return this.usuClave;
    }
    
    public void setUsuClave(String usuClave) {
        this.usuClave = usuClave;
    }
    public Set<Pedidos> getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set<Pedidos> pedidoses) {
        this.pedidoses = pedidoses;
    }
    public Set<Direcciones> getDireccioneses() {
        return this.direccioneses;
    }
    
    public void setDireccioneses(Set<Direcciones> direccioneses) {
        this.direccioneses = direccioneses;
    }




}


